name: Mastodon build

run-name: Mastodon build

on:
  push:
    tags:
      - "v*.*.*"
      
env:
  MASTODON_VERSION: 4.2.1

jobs:
  mastodon-build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - run: sudo apt update

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: >
            ruby3.0 ruby3.0-dev ruby-rubygems gcc build-essential g++ protobuf-compiler autoconf bison
            libxml2-dev libxslt1-dev libgdbm-dev libreadline-dev libprotobuf-dev libssl-dev libyaml-dev libffi-dev libicu-dev libjemalloc-dev zlib1g-dev libidn11-dev libpq-dev
          version: 1.0
          
      - uses: actions/checkout@v3
        with:
          path: ./binary/
          
      - uses: actions/checkout@v3
        with:
          repository: mastodon/mastodon
          ref: v${{ env.MASTODON_VERSION }}
          path: ./binary/opt/mastodon
        
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: ./binary/opt/mastodon/yarn.lock

      - run: sudo gem install bundler

      - run: bundle config deployment 'true'
        working-directory: ./binary/opt/mastodon

      - run: bundle config without 'development test'
        working-directory: ./binary/opt/mastodon

      - run: bundle install
        working-directory: ./binary/opt/mastodon
     
      - run: OTP_SECRET=x SECRET_KEY_BASE=x RAILS_ENV=production NODE_OPTIONS=--openssl-legacy-provider bundle exec rails assets:precompile
        working-directory: ./binary/opt/mastodon
        
      - run: rm -rf ./binary/.git ./binary/opt/mastodon/.git
      - run: mkdir ./deb
      - run: sed -i "s/_MASTODON_VERSION_/$MASTODON_VERSION/" ./binary/DEBIAN/control
      - run: dpkg-deb --build --root-owner-group binary deb

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: deb/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./deb/mastodon-core_${{ env.MASTODON_VERSION }}_amd64.deb

  mastodon-deploy:
    needs: mastodon-build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
 
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
